language: go

go:
      - 1.7

before_install:
      - sudo apt-get -qq update

install:
      - go get github.com/Masterminds/glide

script:
      - go install -v
          - go test $(glide novendor)

